<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LynxConfig.Config\LynxConfig.Config.csproj" />
      <ProjectReference Include="..\LynxConfig.Parser.Toml\LynxConfig.Parser.Toml.csproj" />
    </ItemGroup>

</Project>
