<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LynxConfig.Core\LynxConfig.Core.csproj" />
      <ProjectReference Include="..\LynxConfig.Parser.Json\LynxConfig.Parser.Json.csproj" />
      <ProjectReference Include="..\LynxConfig.Parser.Toml\LynxConfig.Parser.Toml.csproj" />
      <ProjectReference Include="..\LynxConfig.Parser.Xml\LynxConfig.Parser.Xml.csproj" />
      <ProjectReference Include="..\LynxConfig.Parser.Yaml\LynxConfig.Parser.Yaml.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Interfaces\" />
    </ItemGroup>

</Project>
